# Generated by Django 5.0 on 2025-05-22 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsletterSubscription",
        ),
    ]
