# Generated by Django 5.0 on 2025-05-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_delete_newslettersubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
